### ISSUE TITLE
Styled - referencing another styled component inside a template literal

### ISSUE THREAD

**Issue by felipedeboni** [atlassian-labs/compiled#1314]
**Describe the bug**
I am coming from Styled Components, and the following isn't working.

```js
const Radio = styled.input`
 // some styles...
`

const ReferencesAnotherStyled = styled.span`
  // styles...
  ${Radio}:checked + & {
     // more styles...
  }
`
```

It throws the following error:  "No overload matches this call.", also VS Code already paints everything with red.

**Expected behavior**
Works just like Styled Components and use the interpolation to create a selector.

Something like: 

```css
.radioClass:checked .ReferencesAnotherStyled {
 /* more styles... */
}
```

Not sure if it's supposed to work or not, but I couldn't find an alternative to this, only thing I can think about is adding a className and use it just to reference another element.

**Comment by pancaspe87** [comment]
Hi @felipedeboni,
thanks for raising the issue. 

I don't think there is any reference in the docs ( we need to update them!), but we decided not to support component selectors. 

As a workaround you can use HTML data attributes instead of classNames for the following reasons:

- Data attributes do not prompt the browser to consider repaint or layout calculation
- Data attributes have less usage than class names so unlikely to clash with other CSS selectors
- Data attributes have similar performance to selecting via CSS classes

cc @at-nathan , @JakeLane in case you want to add other recommendations

**Comment by at-nathan** [comment]
Because of the atomic nature of Compiled styles, there would an overhead to support this. Seeing that not all components need this and there is a native HTML & CSS alternative, it be preferable to avoid the overhead.  If your component's usage is wide spread you can add a universal selector with a wrapper like so:
```
const RadioStyles = styled.input({ ... });

export const RADIO_SELECTOR = "...";
export const Radio = (props) => <RadioStyles data-component-selector={RADIO_SELECTOR} {...props} />

const ReferencesAnotherStyled = styled.span`
  // styles...
  [data-component-selector="${RADIO_SELECTOR}"]:checked + & {
     // more styles...
  }
`
```
