### ISSUE TITLE
Code mod from css prop

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#179]
We have an internal code mod that we used from styled components to emotion. Let's re-use that.

**Comment by ramblingenzyme** [comment]
Are we going to see Atlaskit components migrate to this from Emotion? Does this mean you've completed the styled-components v3 to Emotion migration in all Atlaskit components?

Thanks,
Satvik
Developer, Easy Agile

**Comment by madou** [comment]
Hello 🙂

Not yet but we are working through them 🤞

**Comment by ramblingenzyme** [comment]
Thanks for the quick reply!

**Comment by pgmanutd** [comment]
@madou: Should I take a look at this one?

**Comment by madou** [comment]
that would be slick, yeah!

we actually have a code mod in atlassian frontend that you can take inspiration from.

**Comment by pgmanutd** [comment]
yups liked the idea.. 😄 will pick this up..we can follow versioning same way we do in [Atlaskit codemods](https://atlaskit.atlassian.com/docs/guides/atlassian-codemods#authoring-codemods)

**Comment by pgmanutd** [comment]
@madou: Should we cover [this section](https://compiledcssinjs.com/docs/migrating#generating-css-at-runtime) also in this code mod?

**Comment by madou** [comment]
For now no - but if you can think of any ways we could do it by all means 🙏

**Comment by pgmanutd** [comment]
@madou: I think we are following fixed/locked versioning instead of independent one. I have 2 approaches in my mind:

First one is introducing `@compiled/codemods` package with fixed versioning. We can update its version or code when there is any change in sibling packages. We can also introduce some cli which can work something like this `npx @compiled/codemods <transformer> <path>`

Second one, we can put codemods inside a folder in `@compiled/css-in-js` package (which is already versioned and codemods will remain up to date with the latest code) and ask users to run `jscodeshift -t <transformer> <path>`

**Comment by madou** [comment]
I think the latter because it's less work.. hehee

**Comment by pgmanutd** [comment]
Hey @madou, m stuck with some personal stuff @home..is this on priority? Will try to submit a PR in a week or two..This works right?

**Comment by madou** [comment]
yeah of course no rush
