### ISSUE TITLE
Add support for GatsbyJS

### ISSUE THREAD

**Issue by rozenmd** [atlassian-labs/compiled#183]
As GatsbyJS doesn't give you direct access to a `.babelrc` file, we'd need a gatsbyjs plugin to support using `@compiled/babel-plugin-css-in-js`.

Here's an example of how the official Emotion plugin for Gatsby works:
https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-emotion

**Comment by madou** [comment]
nice! if you've used project references from typescript it'll be easier - but basically steps to add a new package

1. add new file under https://github.com/atlassian-labs/compiled-css-in-js/tree/master/packages - `gatsby` maybe? can the package be called `@compiled/gatsby-css-in-js`? or it needs to start with `gatsby` - maybe copy paste from `babel` pkg
2. update https://github.com/atlassian-labs/compiled-css-in-js/blob/master/packages/tsconfig.json and put the new package path in it
3. make sure the tsconfig.json references `babel` pkg in it similar to https://github.com/atlassian-labs/compiled-css-in-js/blob/master/packages/babel-plugin/tsconfig.json
4. just do the work :) - how do you think we can test this easily?

**Comment by rozenmd** [comment]
Yeah needs to start with `gatsby-plugin-` unfortunately, will give it a crack tonight

**Comment by rozenmd** [comment]
Hmm, not even sure this warrants a plugin. 

You just need to add the following to the `gatsby-node.js` file:

```
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name: require.resolve(`@compiled/babel-plugin-css-in-js`),
  });
};
```

**Comment by madou** [comment]
if the gatsby plugin streamlines it by just _installing_ it and then its usable - aka "0 config" - i think its still worthwhile making :)

**Comment by JM-Mendez** [comment]
Just stumbled upon this issue while reviewing the lib. In case anyone else is interested, gatsby does allow using a custom `babelrc` config. 

Here are the instructions. 
https://www.gatsbyjs.org/docs/babel/#how-to-use-a-custom-babelrc-file

**Comment by madou** [comment]
thanks @JM-Mendez ! do you think it's worthwhile making a plugin or just adding some installation instructions to the README?

**Comment by JM-Mendez** [comment]
It's a close call between the 2 options. 

Using a custom `babelrc`  is as straightforward as creating the file itself without gatsby. So updating the Readme is a quick fix.

Creating the plugin should only require the code posted by @rozenmd in a plugin package. 

Personally, I think the plugin option is mostly ideal if some gatsby starters are forked to use `@compiled` as the styling solution. Because that would be truly 0 config.

I might have time this upcoming weekend to make a PR for either if you'd like. I may even be able to fork a starter or 2. But can't make any guarantees.

**Comment by hankandre** [comment]
Hi all! I got so excited about Compiled today and wanted to use it for my personal site, so I created the plugin. https://github.com/hankandre/gatsby-plugin-compiled. I haven't published it since it sounded like some folks here might be working on a solution, too.

I'm willing to added it as a package to Compiled, if that's preferable, and I don't mind making a quick Gatsby template, either. 

Let me know if that'd be helpful, or if I'm stepping on toes. I can probably finish it up by EOD tomorrow.

**Comment by madou** [comment]
Hi! That would be neat! Is the information in this issue enough to go on?

**Comment by hankandre** [comment]
I think I have enough to go on, yeah. I got the plugin working for my project, locally, which is pretty exciting. Once it's published I can create a template easily.

Would you all prefer it be added to the monorepo here? I'd assume so for the plugin. I'd imagine the template would just be a bit of an example, but I'd be willing to add both. You all let me know.

**Comment by madou** [comment]
Yes to plugin, unsure about template for now. That's like a starting
template right? Maybe do two PRs one for each and we can talk through the
template one.

**Comment by madou** [comment]
if anyone is interested we'd love a contribution for a package in this repo `@compiled/gatsby-plugin` would be dope!

going to close this off for now as it's not a priority for us.
