### ISSUE TITLE
Investigate perf difference between Babel vs. TS Transformers

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#196]
This won't be a problem for today or for MVP - but eventually we're going to get to scaling problems and it might be worthwhile re-writing to be a Babel plugin.

But! It also might be fine. So let's find out over time.

**Comment by chaffeqa** [comment]
to help migrate / mitigate works, maybe use babel plugin macros?

**Comment by madou** [comment]
Yeah we could definitely write a babel macro today as well. Would you be interested throwing up a spike? (Using the current babel plugin as a base?)

**Comment by chaffeqa** [comment]
sweeeet! so I dont know how to take next steps, plus I'm pretty busy right now (everyone wants web things 🤦‍♀️) so if anyone wants to work on this too let me know, otherwise ill see if i can find some time to make a stab at a PR.

Also, we use jira so I understand the idea of "spike" but dont know how you guys use that in github 😂... so let me know if there are next steps i need for that.

If anyone else is interested in helping please @ me so I can make sure we coordinate / dont duplicate work.

thx fo the quick response @madou !

**Comment by madou** [comment]
all good no pressure :smile:

the spike would be just putting a PR up that has a proof of concept of babel macros working with the current code 👍

**Comment by ankeetmaini** [comment]
Don't we already have the plugin which internally uses ts-transform?

**Comment by madou** [comment]
Yeah we do so there's no major need to go down this path. This is more here for a "what if" scenario 😄

**Comment by madou** [comment]
ok we're going down this path 😄
