### ISSUE TITLE
Investigate baked in styles to start as atomic declarations

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#272]
## Summary

1. Refactor baked in styles to start in atomic form
1. Create a tiny runtime to ensure the last atomic definition of a particular _group_ wins
1. Class names will be hashed and made as short as possible

**These changes would**

1. Enable overrides to work without needing to battle specificity wars
1. Get us a step closer to extracted atomic CSS
1. Make writing the CSS extraction plugin easier because we don't need to re-write class names again
1. Ensure overrides work across different major versions of the library

**Caveats of this change are**

1. Bundle size will go up slightly (which is offset when we end up extracting to CSS)
1. Source maps wouldn't work well anymore

## Background

For background, currently baked in styles looks like this:

```
const MyComponent = styled.div`
  font-size: 12px;
  color: blue;
`;
```

Which would generate this:

```
.cc-abc111 {
  font-size: 12px;
  color: blue;
}

<div class="cc-abc111" />
```

By itself - this works fantastically. But what happens if you want to override something? Well...

```
const WrappedMyComponent = styled(MyComponent)`
  font-size: 15px;
`;
```

Which would then generate this:

```
.cc-abc222 {
  font-size: 15px;
}

<div class="cc-abc111 cc-abc222" />
```

And then we are at the bane of specificity wars to see where the override may, or may not, be applied. This is a problem - and it's a problem for any API not just the styled API.

And what's worse is we can't fundamentally fix it with the current CSS output - we can work around it but there will be small edge cases - such as what happens when you render both the original, and the overridden component - which styles win? It will depend who renders first.

### Styles start in atomic form

Instead of creating single declarations we start with atomic declarations. Looking back at the example above, let's rewrite it with this in mind.

```
const MyComponent = styled.div`
  font-size: 12px;
  color: blue;
`;
```

Which would generate this:

```
.cc-font-size-12 {
  font-size: 12px;
}

.cc-color-blue {
  color: blue;
}

<div class="cc-font-size-12 cc-color-blue" />
```

And what does it look like if we override?

```
const WrappedMyComponent = styled(MyComponent)`
  font-size: 15px;
`;
```

Which would then generate this:

```
.cc-font-size-15 {
  font-size: 15px;
}

<div class="cc-font-size-12 cc-color-blue cc-font-size-15" />
```

Ok so then we have three class names now assigned to this component. But hopefully you see something we can do with this information...

### Runtime to handle atomic declarations

We have a runtime that will iterate through classes and ensure only the last atomic declaration wins.

```
atomic('cc-font-size-12 cc-color-blue cc-font-size-15') // cc-color-blue cc-font-size-15
```

The `cc-font-size-12` class name is removed. Override is applied. No wars to fight. Consistency.

## Formula summarized

To handle all of this:

- Top level declarations
- Nested declarations
- Media queries
- Pseudo selectors
- Dynamic property values

Class names will be generated in the form of:

```
{atrules}{selectors}{propertyname}{propertyvalue}
```

That is then hashed. The atomic declaration runtime will compare `{atrules}{selectors}{propertyname}` and ensure only _the last one_ defined wins.

**Comment by alexreardon** [comment]
Interesting idea!

**Comment by alexreardon** [comment]
Did u consider using inline styles for overrides?

**Comment by madou** [comment]
it was on the back of my mind - but in this scenario it's a bit tricky to do with this kind of API (adding extra styles on to already defined styles)

this approach allows us to have our cake and eat it too - things will just work (with similar constraints to other libraries - such as you need to use the single library to ensure everything works all the same, e.g. emotion).

inline styles is definitely the direction we want to go internally for "official" overrides - this is more of a catch all to ensure things work as expected when using the library in all other scenarios

**Comment by madou** [comment]
im currently spiking out an implementation to see the bundle size impacts (gzipped)

**Comment by alexreardon** [comment]
This is a cool idea though :)

**Comment by asvny** [comment]
A few months ago .. I was researching this topic.
I think this is the right approach to go.  By hashing these attributes, it is deterministic!
```
{prefix}{atrules}{selectors}{propertyname}{propertyvalue}
```

BTW .. this is how react-native-web Stylesheet works and here are some resources that I found useful.
1. https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/exports/StyleSheet/createOrderedCSSStyleSheet.js
2. https://github.com/giuseppeg/style-sheet/blob/master/src/createOrderedCSSStyleSheet.js#L220
3. https://github.com/styletron/styletron/blob/master/packages/styletron-engine-atomic/src/sort-css-media-queries.js

The last rules win is a good approach so that I don't have to worry about CSS cascade or inheritance.

Supporting atomic CSS for all types of selectors is literally impossible without knowing enough information about the template/component. This is were [CSS-Blocks ](https://github.com/linkedin/css-blocks) excel because in their case, they support only a subset and obtains info about the component using static analysis. Wondering if https://github.com/linkedin/opticss might help in this case. 

All I want to support is a small subset of simple selectors and some combinator selectors like `+`, `~` etc..,  in my case. 😇

**Comment by TxHawks** [comment]
Is there a plan on how to handle the order of pseudo selectors when decomposing styles into atomic classes?

The problem is:

```jsx
// component A
<button
  css={{ 
    color: 'red',
    '&:active': {
      color: 'blue',
    },
  }}
>
  I'll be blue when active
</button>;
```

```jsx
// component B
<button
  css={{
    color: 'red',
    '&:focus': {
      color: 'green',
    },   
    '&:active': {
      color: 'blue',
    },
  }}
>
  I'll remain green when active
</button>;
```

When naïvely decomposed to atomic styles, the resulting CSS will be:
```css
.a { color: red; }
.b:active { color: blue; }
.c:focus { color: green; }
```

The person authoring component B will expect the `:active` style to trump the `:focus` style, and text to become green when in the `active` state. However, because `&:active` was declared before, in component A, the `:active` style precedes the `:focus` style, and due to the nature of the CSS cascade, `:focus` will take precedence.

I can think of two ways to get around this, both based on standardizing pseudo-selector precedence (lvhfa or lvfha):
   1.  Sorting the styles in the stylesheet based on the standard. This is how [Fela](https://github.com/robinweser/fela/) handles this, and I've started working on a [PostCSS](https://github.com/TxHawks/postcss-sort-lvfha) plugin doing the same, though I've never quite got it ready to be released.
  2. Using specificity to enforce the standard, so that the CSS file looks something like this:
```css
/*
chain twice for `:link`, three times for `:visited`, four time for `:focus`,
five times for `:hover` and six for `:active`
*/
.a { color: red; }
.b.b.b.b.b.b:active { color: blue; }
.c.c.c.c:focus { color: green; }
```

I personally prefer the first approach, as the cascade is easier to override than inflated specificity.

**Comment by madou** [comment]
Thanks so much for chiming in dude! I love Github for this reason ❤️ 

Yeah I think you're right - (1) seems way more ideal. (2) would be slippery slope to a world of duplicated declarations, and pain.

I'll spike something out with this in mind.

**Comment by madou** [comment]
The spike has been completed and we are going forward with this implementation. This has been split up into smaller tickets:

- https://github.com/atlassian-labs/compiled/issues/286
- https://github.com/atlassian-labs/compiled/issues/287
- https://github.com/atlassian-labs/compiled/issues/288
- https://github.com/atlassian-labs/compiled/issues/289
- https://github.com/atlassian-labs/compiled/issues/290
