### ISSUE TITLE
Update stylesheet runtime to order psuedo state atomic declarations based on lvfha

### ISSUE THREAD

**Issue by madou** [atlassian-labs/compiled#290]
Atomic declarations means user land ordering of pseudo states no longer is possible. We are going to bake in the order based on LVFHA:

Top to bottom, bottom takes precedence:

- `:link`
- `:visited`
- `:focus`
- `:hover`
- `:active`

This ticket will modify the `stylesheet` runtime (used only when styles are baked in - once extracted this runtime is removed) to ensure the ordering.

One idea  I have for this is to build the class name with knowledge of the pseudo state so we don't have to do much at runtime.

Guiding principles:

1. less is more
1. code short as possible

**Comment by pgmanutd** [comment]
@madou: So here are my findings:

1. When we are rendering two components (with pseudo states in random order but components in given order): 

![image](https://user-images.githubusercontent.com/7638708/95603832-71672000-0a74-11eb-9cf2-33c8961decd2.png)

`hover` variable in above image is

```typescript
export const hover = {
  color: 'purple',
  backgroundColor: 'red',
};
```

I was able to re-arrange them in correct **lvfha** order as you can see below:

![image](https://user-images.githubusercontent.com/7638708/95605204-3b2aa000-0a76-11eb-81d3-e0598178e98c.png)

but with a caveat i.e. `._1xir13q2:active{color:blue}` style is repeated again because I have to override the previous same `._1xir13q2:active{color:blue}` style when second component is rendered in order to maintain **lvfha** order for both of them (because of atomicity). Though I can fix (should we do this?) this by doing something like this (we can remove previous style element with same `textContent`):
```typescript
const styleElementFound = Array.from(document.querySelectorAll('style')).find(
  // styleElement.textContent will be ._1xir13q2:active{color:blue}
  (styleElement) => styleElement.textContent?.trim() === sheet.trim() 
);

if (!!styleElementFound) {
  styleElementFound.remove();
}
```

What are your thoughts on this ^^?

2. Man, AtRules are challenging. When we are rendering same two components (as above) with some AtRules along with pseudo states:

![image](https://user-images.githubusercontent.com/7638708/95606512-0e778800-0a78-11eb-9360-a0c8dde6abb9.png)

following sheets are generated for these two components:

```typescript
[
  "._dj7i1txw{display:flex}", 
  "._36l612am{font-size:50px}", 
  "._1doq13q2{color:blue}", 
  "._1xir13q2:active{color:blue}"
]

[
  "._dj7i1txw{display:flex}", 
  "._36l612am{font-size:50px}", 
  "._1doq1cnh{color:purple}", 
  "._1uhh1cnh:hover{color:purple}", 
  "._747x5scu:hover{background-color:red}", 
  "._1xir13q2:active{color:blue}", 
  "._t5glbf54:focus{color:green}", 
  "@media (max-width: 400px){@supports (display: grid){._12535scu:active{color:red}._1ixm32ev:focus{color:pink}}}"
]
```

Look at this one:
`@media (max-width: 400px){@supports (display: grid){._12535scu:active{color:red}._1ixm32ev:focus{color:pink}}}`

This is a string, not a separate sheet for each rule. We might have to change complete architecture of `atomicify-rules` postcss plugin (I can be wrong here). Instead of sending sheets as flat structure, we have to create a tree and let runtime handle the ordering and insertion part (depending on value type). Something like this:

```typescript
[
  "._dj7i1txw{display:flex}", 
  "._36l612am{font-size:50px}", 
  "._1doq1cnh{color:purple}", 
  "._1uhh1cnh:hover{color:purple}", 
  "._747x5scu:hover{background-color:red}", 
  "._1xir13q2:active{color:blue}", 
  "._t5glbf54:focus{color:green}", 
 { 
   parent:  "@media (max-width: 400px)",
   child: {
     parent: "@supports (display: grid)".
     child: ["._12535scu:active{color:red}", "._1ixm32ev:focus{color:pink}" ]
   }
 }
]
```

What are your thoughts on this one also ^^?

**Comment by madou** [comment]
good work so far @pgmanutd

> Though I can fix (should we do this?) this by doing something like this (we can remove previous style element with same textContent):

if we can avoid it we don't want any duplicate declarations during runtime - it ends up causing developer confusion in dev tools (like so):

![image](https://user-images.githubusercontent.com/6801309/95693640-1ce0c200-0c79-11eb-8510-cf9bf1b01a66.png)

what if instead of trying to re-order a single grouping of styles (which is kind of complicated at runtime) we introduce the concept of style "buckets"?

```html
// catch all styles
<style data-compiled-style />

// LVFHA ordering
<style data-compiled-link />
<style data-compiled-visited />
<style data-compiled-focus />
<style data-compiled-hover />
<style data-compiled-active />

// media
<style data-compiled-media />
```

1. the catch all bucket would be the first
1. then we have a bucket for each pseduo selector of LVFHA
1. then we have media queries defined last to always take precedence when active
1. if possible we "lazily" add buckets - if one hasn't been used we don't bother adding it preemptively

one edge case would be ensuring ordering of LVFHA inside at rules - perhaps we just statically order them in their respective stylesheet and for now that's "good enough"?

**Before**

```css
@media screen {
  :focus {
    color: blue;
  }
  :hover {
    color: red;
  }
}
```

**After**

```css
@media screen {
  :hover {
    color: red;
  }
  :focus {
    color: blue;
  }
}
```

finally we then just utilise the current stylesheet with the addition of the bucket:

```js
stylesheet('._dj7i1txw{display:flex}', 'style');
stylesheet('._1uhh1cnh:hover{color:purple}', 'hover');
```

(or alternatively just have this logic inside sheet which would make more sense, but you get the idea 😄

> Instead of sending sheets as flat structure, we have to create a tree and let runtime handle the ordering and insertion part (depending on value type)

I like this idea - but perhaps we don't need to worry about this for now. If you look at the above and assume all media queries are "localized" - aka we order LVFHA within an at rule - perhaps that's good enough for now?

**Comment by alexreardon** [comment]
> if we can avoid it we don't want any duplicate declarations during runtime - it ends up causing developer confusion in dev tools (like so):

This is a concern for sure. But I personally wouldn't go rebuild lots of things to avoid it

**Comment by madou** [comment]
Agreed 😄

**Comment by madou** [comment]
@pgmanutd there is also some new pseduo selectors - `:focus-visible` - that we'll need to consider as well. probably slot it in after `:focus`


- :link
- :visited
- :focus
**- :focus-visible**
- :hover
- :active

**Comment by TxHawks** [comment]
There's also `:focus-within`, that should probably come before `:focus`
