### ISSUE TITLE
Composition of styled components with atomic css output

### ISSUE THREAD

**Issue by TxHawks** [atlassian-labs/compiled#319]
Not sure if composition is already implemented in this way, but the ability to compose reusable components is crucial. As touched on in [#312 (comment)](https://github.com/atlassian-labs/compiled/issues/312#issuecomment-706924766), it allows for very easy extension and modification of exiting components, while largely remaining statically analyzable . 

However, when outputting atomic styles, there are a few challenges:

Say we have the following reusable component
```tsx
// assuming resulting classes are `a`, `b` and `c`
const BaseBox = styled.div<{ size: number, }>`
  background-color: #ccc;
  height: ${props => props.size};
  width: ${props => props.size};
`;  
``` 

When composed this way:

```tsx
const MyBox = styles(BaseBox)`
    background-color: #333;
`;
```

Libraries often ensure the right styles are applied in such cases through specificity or the cascade. But in an atomic world, specificity is flat, and cascade order can not e relied on. Hence, precedence must e determined on usage rather than definition, and class `a` (`background-color: #ccc`) should be removed from the html in favor of class `d` (`background-color: #333`). 

Optimally, in cases where`BaseBox` is used in composition with components that override `background-color`, the `background-color: #ccc` ruleset shouldn't exist in the CSS at all rather than just be removed from the html.

Since this is all statically analyzable, it should be possible to achieve in a compiled paradigm and is a significant win for both usability and performance.

**Comment by madou** [comment]
Hi! Thanks for raising this.

This has been implemented 😄. One of our guiding principles is to ensure familiar behaviour when migrating from emotion/styled components - so much so that if we _didn't_ we wouldn't be able to safely migrate Atlassian to this library.

At the moment the implementation goes at this in two angles:

1. Static generation of atomic rules with "groups" https://github.com/atlassian-labs/compiled/blob/master/packages/css/src/plugins/atomicify-rules.tsx#L28
2. A small runtime (very similar to how `classnames` works) to ensure the "last defined group wins" https://github.com/atlassian-labs/compiled/blob/master/packages/runtime/src/ax.tsx#L22

We've spoken internally in the team about potentially going a step further and completely doing this at build time - but it goes against our target of both delivering baked in styles and then in application - extracting to CSS.

I think when we get the the CSS extraction story some extra optimizations will make themselves apparent and we'll re-evaluate then what makes sense to invest in.

Let me know if you have any thoughts else let's close this off 😄

**Comment by TxHawks** [comment]
Thanks for the code references. I've een meaning to dive deeper into the code since the docs are now quite dated, but didn't have the time yet. This helps.

**Comment by madou** [comment]
No worries! We'll be updating the docs in a monthish when we've cut the first release of the refactor 😄.

As a side - thanks so much for chiming in every now and then! Super helpful - keep it up
